version: '3'
services:
  server:
    container_name: utl-server-dev
    build:
        context: ./server
    ports:
     - "3001:3001"
      - "3306:3306"
    restart: always
    volumes:
      - ./server:/server
      - /server/node_modules
    command: nodemon /server/index.js

  client:
    container_name: utl-client-dev
    build:
        context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    command: npm start

volumes:
  db_data:
