version: '3'
services:
  server:
    container_name: utl-server-dev
    build:
        context: ./server
    ports:
     - "3001:3001"
    links:
      - mysql
    volumes:
      - ./server/scripts:/server/scripts
      - ./server/src:/server/src
    command: nodemon /server/index.js

  client:
    container_name: utl-client-dev
    build:
        context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/public:/client/public
      - ./client/src:/client/src
    command: npm start

  phpmyadmin:
    container_name: utl-phpmyadmin-dev
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'

  mysql:
    container_name: utl-mysql-dev
    image: mysql:5.7.24
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
      MYSQL_DATABASE: utl
    restart: always
    ports:
      - 3306:3306

volumes:
  db_data:
